### ISSUE TITLE
Error establishing a database connection on local MAMP

### ISSUE THREAD

**Issue by sammdec** [markjaquith/WordPress-Skeleton#2]
just a quick question but when i install this on my local system and go to the route it does not start the wordpress installation but display the dreaded error establishing db connection. 
Therefore do i need to create the database and all the tables for a site manually or is there an automatic way of doing this using this skeleton setup?

**Comment by ShovanSargunam** [comment]
Hi I am having the same issue. 
Currently wp-config.php has

`if ( file_exists( dirname( __FILE__ ) . '/local-config.php' ) ) {
	define( 'WP_LOCAL_DEV', true );
	include( dirname( __FILE__ ) . '/local-config.php' );
} else {
	define( 'WP_LOCAL_DEV', false );
	define( 'DB_NAME', '%%DB_NAME%%' );
	define( 'DB_USER', '%%DB_USER%%' );
	define( 'DB_PASSWORD', '%%DB_PASSWORD%%' );
	define( 'DB_HOST', '%%DB_HOST%%' ); // Probably 'localhost'
}`

local-config.php has
`define( 'DB_NAME', 'websitedev' );
define( 'DB_USER', 'websitedev' );
define( 'DB_PASSWORD', 'asdqE23ER' );
define( 'DB_HOST', 'localhost' ); // Probably 'localhost'`

When I install the site I get the following error

<hr />
Error establishing a database connection
This either means that the username and password information in your wp-config.php file is incorrect or we can't contact the database server at localhost. This could mean your host's database server is down.

Are you sure you have the correct username and password?
Are you sure that you have typed the correct hostname?
Are you sure that the database server is running?`
<hr />

However when I replace wp-config with 

`define( 'DB_NAME', 'websitedev' );
define( 'DB_USER', 'websitedev' );
define( 'DB_PASSWORD', 'asdqE23ER' );
define( 'DB_HOST', 'localhost' ); // Probably 'localhost'`

It works.

ps: I have tested database connection it works. What is the issue here?

**Comment by byNiko** [comment]
You probably mass uploaded all files to the live server -  including the local-config.php file. Delete that file on the live server.  Keep it on your local.

The wp-config file in this repo checks if the local file exists. If it exists it supercedes the wp-config database login info. So effectively your live server uses the credentials for your local server.
